[package]
name = "school-collect-migrator"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
school-collect-db = { path = "../../crates/db" }
school-collect-observability = { path = "../../crates/observability" }
tokio = { workspace = true }
