-- 2026 학교폭력 예방교육 학급운영 물품 구입 목록 템플릿 등록 SQL
-- Supabase Dashboard → SQL Editor에서 실행
-- collect_runs는 마감일이 정해진 뒤 앱의 '새 수합'에서 생성하세요.

DO $$
DECLARE
  v_template_id uuid;
BEGIN
  SELECT id INTO v_template_id
  FROM form_templates
  WHERE title = '2026 학교폭력 예방교육 학급운영 물품 구입 목록' AND year = 2026
  LIMIT 1;

  IF v_template_id IS NULL THEN
    INSERT INTO form_templates (title, description, year)
    VALUES ('2026 학교폭력 예방교육 학급운영 물품 구입 목록', '학급당 10만원 이내로 학교폭력 예방교육 학급운영 물품 구입 목록을 입력합니다. 학년별 취합이 가능하도록 학년/반 정보를 정확히 입력합니다.', 2026)
    RETURNING id INTO v_template_id;
  ELSE
    UPDATE form_templates
    SET description = '학급당 10만원 이내로 학교폭력 예방교육 학급운영 물품 구입 목록을 입력합니다. 학년별 취합이 가능하도록 학년/반 정보를 정확히 입력합니다.', updated_at = now()
    WHERE id = v_template_id;

    DELETE FROM form_fields WHERE template_id = v_template_id;
  END IF;

  INSERT INTO form_fields (template_id, label, field_type, required, options, "order")
  VALUES
    (v_template_id, '물품01_물품명', 'text', false, NULL::jsonb, 0),
    (v_template_id, '물품01_예상단가', 'number', false, NULL::jsonb, 1),
    (v_template_id, '물품01_수량', 'number', false, NULL::jsonb, 2),
    (v_template_id, '물품01_예상금액', 'number', false, NULL::jsonb, 3),
    (v_template_id, '물품01_할인가', 'number', false, NULL::jsonb, 4),
    (v_template_id, '물품01_사는곳', 'text', false, NULL::jsonb, 5),
    (v_template_id, '물품01_상품번호_링크', 'textarea', false, NULL::jsonb, 6),
    (v_template_id, '물품02_물품명', 'text', false, NULL::jsonb, 7),
    (v_template_id, '물품02_예상단가', 'number', false, NULL::jsonb, 8),
    (v_template_id, '물품02_수량', 'number', false, NULL::jsonb, 9),
    (v_template_id, '물품02_예상금액', 'number', false, NULL::jsonb, 10),
    (v_template_id, '물품02_할인가', 'number', false, NULL::jsonb, 11),
    (v_template_id, '물품02_사는곳', 'text', false, NULL::jsonb, 12),
    (v_template_id, '물품02_상품번호_링크', 'textarea', false, NULL::jsonb, 13),
    (v_template_id, '물품03_물품명', 'text', false, NULL::jsonb, 14),
    (v_template_id, '물품03_예상단가', 'number', false, NULL::jsonb, 15),
    (v_template_id, '물품03_수량', 'number', false, NULL::jsonb, 16),
    (v_template_id, '물품03_예상금액', 'number', false, NULL::jsonb, 17),
    (v_template_id, '물품03_할인가', 'number', false, NULL::jsonb, 18),
    (v_template_id, '물품03_사는곳', 'text', false, NULL::jsonb, 19),
    (v_template_id, '물품03_상품번호_링크', 'textarea', false, NULL::jsonb, 20),
    (v_template_id, '물품04_물품명', 'text', false, NULL::jsonb, 21),
    (v_template_id, '물품04_예상단가', 'number', false, NULL::jsonb, 22),
    (v_template_id, '물품04_수량', 'number', false, NULL::jsonb, 23),
    (v_template_id, '물품04_예상금액', 'number', false, NULL::jsonb, 24),
    (v_template_id, '물품04_할인가', 'number', false, NULL::jsonb, 25),
    (v_template_id, '물품04_사는곳', 'text', false, NULL::jsonb, 26),
    (v_template_id, '물품04_상품번호_링크', 'textarea', false, NULL::jsonb, 27),
    (v_template_id, '물품05_물품명', 'text', false, NULL::jsonb, 28),
    (v_template_id, '물품05_예상단가', 'number', false, NULL::jsonb, 29),
    (v_template_id, '물품05_수량', 'number', false, NULL::jsonb, 30),
    (v_template_id, '물품05_예상금액', 'number', false, NULL::jsonb, 31),
    (v_template_id, '물품05_할인가', 'number', false, NULL::jsonb, 32),
    (v_template_id, '물품05_사는곳', 'text', false, NULL::jsonb, 33),
    (v_template_id, '물품05_상품번호_링크', 'textarea', false, NULL::jsonb, 34),
    (v_template_id, '물품06_물품명', 'text', false, NULL::jsonb, 35),
    (v_template_id, '물품06_예상단가', 'number', false, NULL::jsonb, 36),
    (v_template_id, '물품06_수량', 'number', false, NULL::jsonb, 37),
    (v_template_id, '물품06_예상금액', 'number', false, NULL::jsonb, 38),
    (v_template_id, '물품06_할인가', 'number', false, NULL::jsonb, 39),
    (v_template_id, '물품06_사는곳', 'text', false, NULL::jsonb, 40),
    (v_template_id, '물품06_상품번호_링크', 'textarea', false, NULL::jsonb, 41),
    (v_template_id, '물품07_물품명', 'text', false, NULL::jsonb, 42),
    (v_template_id, '물품07_예상단가', 'number', false, NULL::jsonb, 43),
    (v_template_id, '물품07_수량', 'number', false, NULL::jsonb, 44),
    (v_template_id, '물품07_예상금액', 'number', false, NULL::jsonb, 45),
    (v_template_id, '물품07_할인가', 'number', false, NULL::jsonb, 46),
    (v_template_id, '물품07_사는곳', 'text', false, NULL::jsonb, 47),
    (v_template_id, '물품07_상품번호_링크', 'textarea', false, NULL::jsonb, 48),
    (v_template_id, '물품08_물품명', 'text', false, NULL::jsonb, 49),
    (v_template_id, '물품08_예상단가', 'number', false, NULL::jsonb, 50),
    (v_template_id, '물품08_수량', 'number', false, NULL::jsonb, 51),
    (v_template_id, '물품08_예상금액', 'number', false, NULL::jsonb, 52),
    (v_template_id, '물품08_할인가', 'number', false, NULL::jsonb, 53),
    (v_template_id, '물품08_사는곳', 'text', false, NULL::jsonb, 54),
    (v_template_id, '물품08_상품번호_링크', 'textarea', false, NULL::jsonb, 55),
    (v_template_id, '물품09_물품명', 'text', false, NULL::jsonb, 56),
    (v_template_id, '물품09_예상단가', 'number', false, NULL::jsonb, 57),
    (v_template_id, '물품09_수량', 'number', false, NULL::jsonb, 58),
    (v_template_id, '물품09_예상금액', 'number', false, NULL::jsonb, 59),
    (v_template_id, '물품09_할인가', 'number', false, NULL::jsonb, 60),
    (v_template_id, '물품09_사는곳', 'text', false, NULL::jsonb, 61),
    (v_template_id, '물품09_상품번호_링크', 'textarea', false, NULL::jsonb, 62),
    (v_template_id, '물품10_물품명', 'text', false, NULL::jsonb, 63),
    (v_template_id, '물품10_예상단가', 'number', false, NULL::jsonb, 64),
    (v_template_id, '물품10_수량', 'number', false, NULL::jsonb, 65),
    (v_template_id, '물품10_예상금액', 'number', false, NULL::jsonb, 66),
    (v_template_id, '물품10_할인가', 'number', false, NULL::jsonb, 67),
    (v_template_id, '물품10_사는곳', 'text', false, NULL::jsonb, 68),
    (v_template_id, '물품10_상품번호_링크', 'textarea', false, NULL::jsonb, 69),
    (v_template_id, '물품11_물품명', 'text', false, NULL::jsonb, 70),
    (v_template_id, '물품11_예상단가', 'number', false, NULL::jsonb, 71),
    (v_template_id, '물품11_수량', 'number', false, NULL::jsonb, 72),
    (v_template_id, '물품11_예상금액', 'number', false, NULL::jsonb, 73),
    (v_template_id, '물품11_할인가', 'number', false, NULL::jsonb, 74),
    (v_template_id, '물품11_사는곳', 'text', false, NULL::jsonb, 75),
    (v_template_id, '물품11_상품번호_링크', 'textarea', false, NULL::jsonb, 76),
    (v_template_id, '물품12_물품명', 'text', false, NULL::jsonb, 77),
    (v_template_id, '물품12_예상단가', 'number', false, NULL::jsonb, 78),
    (v_template_id, '물품12_수량', 'number', false, NULL::jsonb, 79),
    (v_template_id, '물품12_예상금액', 'number', false, NULL::jsonb, 80),
    (v_template_id, '물품12_할인가', 'number', false, NULL::jsonb, 81),
    (v_template_id, '물품12_사는곳', 'text', false, NULL::jsonb, 82),
    (v_template_id, '물품12_상품번호_링크', 'textarea', false, NULL::jsonb, 83),
    (v_template_id, '물품13_물품명', 'text', false, NULL::jsonb, 84),
    (v_template_id, '물품13_예상단가', 'number', false, NULL::jsonb, 85),
    (v_template_id, '물품13_수량', 'number', false, NULL::jsonb, 86),
    (v_template_id, '물품13_예상금액', 'number', false, NULL::jsonb, 87),
    (v_template_id, '물품13_할인가', 'number', false, NULL::jsonb, 88),
    (v_template_id, '물품13_사는곳', 'text', false, NULL::jsonb, 89),
    (v_template_id, '물품13_상품번호_링크', 'textarea', false, NULL::jsonb, 90),
    (v_template_id, '물품14_물품명', 'text', false, NULL::jsonb, 91),
    (v_template_id, '물품14_예상단가', 'number', false, NULL::jsonb, 92),
    (v_template_id, '물품14_수량', 'number', false, NULL::jsonb, 93),
    (v_template_id, '물품14_예상금액', 'number', false, NULL::jsonb, 94),
    (v_template_id, '물품14_할인가', 'number', false, NULL::jsonb, 95),
    (v_template_id, '물품14_사는곳', 'text', false, NULL::jsonb, 96),
    (v_template_id, '물품14_상품번호_링크', 'textarea', false, NULL::jsonb, 97),
    (v_template_id, '물품15_물품명', 'text', false, NULL::jsonb, 98),
    (v_template_id, '물품15_예상단가', 'number', false, NULL::jsonb, 99),
    (v_template_id, '물품15_수량', 'number', false, NULL::jsonb, 100),
    (v_template_id, '물품15_예상금액', 'number', false, NULL::jsonb, 101),
    (v_template_id, '물품15_할인가', 'number', false, NULL::jsonb, 102),
    (v_template_id, '물품15_사는곳', 'text', false, NULL::jsonb, 103),
    (v_template_id, '물품15_상품번호_링크', 'textarea', false, NULL::jsonb, 104),
    (v_template_id, '물품16_물품명', 'text', false, NULL::jsonb, 105),
    (v_template_id, '물품16_예상단가', 'number', false, NULL::jsonb, 106),
    (v_template_id, '물품16_수량', 'number', false, NULL::jsonb, 107),
    (v_template_id, '물품16_예상금액', 'number', false, NULL::jsonb, 108),
    (v_template_id, '물품16_할인가', 'number', false, NULL::jsonb, 109),
    (v_template_id, '물품16_사는곳', 'text', false, NULL::jsonb, 110),
    (v_template_id, '물품16_상품번호_링크', 'textarea', false, NULL::jsonb, 111),
    (v_template_id, '물품17_물품명', 'text', false, NULL::jsonb, 112),
    (v_template_id, '물품17_예상단가', 'number', false, NULL::jsonb, 113),
    (v_template_id, '물품17_수량', 'number', false, NULL::jsonb, 114),
    (v_template_id, '물품17_예상금액', 'number', false, NULL::jsonb, 115),
    (v_template_id, '물품17_할인가', 'number', false, NULL::jsonb, 116),
    (v_template_id, '물품17_사는곳', 'text', false, NULL::jsonb, 117),
    (v_template_id, '물품17_상품번호_링크', 'textarea', false, NULL::jsonb, 118),
    (v_template_id, '물품18_물품명', 'text', false, NULL::jsonb, 119),
    (v_template_id, '물품18_예상단가', 'number', false, NULL::jsonb, 120),
    (v_template_id, '물품18_수량', 'number', false, NULL::jsonb, 121),
    (v_template_id, '물품18_예상금액', 'number', false, NULL::jsonb, 122),
    (v_template_id, '물품18_할인가', 'number', false, NULL::jsonb, 123),
    (v_template_id, '물품18_사는곳', 'text', false, NULL::jsonb, 124),
    (v_template_id, '물품18_상품번호_링크', 'textarea', false, NULL::jsonb, 125),
    (v_template_id, '물품19_물품명', 'text', false, NULL::jsonb, 126),
    (v_template_id, '물품19_예상단가', 'number', false, NULL::jsonb, 127),
    (v_template_id, '물품19_수량', 'number', false, NULL::jsonb, 128),
    (v_template_id, '물품19_예상금액', 'number', false, NULL::jsonb, 129),
    (v_template_id, '물품19_할인가', 'number', false, NULL::jsonb, 130),
    (v_template_id, '물품19_사는곳', 'text', false, NULL::jsonb, 131),
    (v_template_id, '물품19_상품번호_링크', 'textarea', false, NULL::jsonb, 132),
    (v_template_id, '물품20_물품명', 'text', false, NULL::jsonb, 133),
    (v_template_id, '물품20_예상단가', 'number', false, NULL::jsonb, 134),
    (v_template_id, '물품20_수량', 'number', false, NULL::jsonb, 135),
    (v_template_id, '물품20_예상금액', 'number', false, NULL::jsonb, 136),
    (v_template_id, '물품20_할인가', 'number', false, NULL::jsonb, 137),
    (v_template_id, '물품20_사는곳', 'text', false, NULL::jsonb, 138),
    (v_template_id, '물품20_상품번호_링크', 'textarea', false, NULL::jsonb, 139),
    (v_template_id, '물품21_물품명', 'text', false, NULL::jsonb, 140),
    (v_template_id, '물품21_예상단가', 'number', false, NULL::jsonb, 141),
    (v_template_id, '물품21_수량', 'number', false, NULL::jsonb, 142),
    (v_template_id, '물품21_예상금액', 'number', false, NULL::jsonb, 143),
    (v_template_id, '물품21_할인가', 'number', false, NULL::jsonb, 144),
    (v_template_id, '물품21_사는곳', 'text', false, NULL::jsonb, 145),
    (v_template_id, '물품21_상품번호_링크', 'textarea', false, NULL::jsonb, 146),
    (v_template_id, '물품22_물품명', 'text', false, NULL::jsonb, 147),
    (v_template_id, '물품22_예상단가', 'number', false, NULL::jsonb, 148),
    (v_template_id, '물품22_수량', 'number', false, NULL::jsonb, 149),
    (v_template_id, '물품22_예상금액', 'number', false, NULL::jsonb, 150),
    (v_template_id, '물품22_할인가', 'number', false, NULL::jsonb, 151),
    (v_template_id, '물품22_사는곳', 'text', false, NULL::jsonb, 152),
    (v_template_id, '물품22_상품번호_링크', 'textarea', false, NULL::jsonb, 153),
    (v_template_id, '물품23_물품명', 'text', false, NULL::jsonb, 154),
    (v_template_id, '물품23_예상단가', 'number', false, NULL::jsonb, 155),
    (v_template_id, '물품23_수량', 'number', false, NULL::jsonb, 156),
    (v_template_id, '물품23_예상금액', 'number', false, NULL::jsonb, 157),
    (v_template_id, '물품23_할인가', 'number', false, NULL::jsonb, 158),
    (v_template_id, '물품23_사는곳', 'text', false, NULL::jsonb, 159),
    (v_template_id, '물품23_상품번호_링크', 'textarea', false, NULL::jsonb, 160),
    (v_template_id, '물품24_물품명', 'text', false, NULL::jsonb, 161),
    (v_template_id, '물품24_예상단가', 'number', false, NULL::jsonb, 162),
    (v_template_id, '물품24_수량', 'number', false, NULL::jsonb, 163),
    (v_template_id, '물품24_예상금액', 'number', false, NULL::jsonb, 164),
    (v_template_id, '물품24_할인가', 'number', false, NULL::jsonb, 165),
    (v_template_id, '물품24_사는곳', 'text', false, NULL::jsonb, 166),
    (v_template_id, '물품24_상품번호_링크', 'textarea', false, NULL::jsonb, 167),
    (v_template_id, '물품25_물품명', 'text', false, NULL::jsonb, 168),
    (v_template_id, '물품25_예상단가', 'number', false, NULL::jsonb, 169),
    (v_template_id, '물품25_수량', 'number', false, NULL::jsonb, 170),
    (v_template_id, '물품25_예상금액', 'number', false, NULL::jsonb, 171),
    (v_template_id, '물품25_할인가', 'number', false, NULL::jsonb, 172),
    (v_template_id, '물품25_사는곳', 'text', false, NULL::jsonb, 173),
    (v_template_id, '물품25_상품번호_링크', 'textarea', false, NULL::jsonb, 174),
    (v_template_id, '물품26_물품명', 'text', false, NULL::jsonb, 175),
    (v_template_id, '물품26_예상단가', 'number', false, NULL::jsonb, 176),
    (v_template_id, '물품26_수량', 'number', false, NULL::jsonb, 177),
    (v_template_id, '물품26_예상금액', 'number', false, NULL::jsonb, 178),
    (v_template_id, '물품26_할인가', 'number', false, NULL::jsonb, 179),
    (v_template_id, '물품26_사는곳', 'text', false, NULL::jsonb, 180),
    (v_template_id, '물품26_상품번호_링크', 'textarea', false, NULL::jsonb, 181),
    (v_template_id, '물품27_물품명', 'text', false, NULL::jsonb, 182),
    (v_template_id, '물품27_예상단가', 'number', false, NULL::jsonb, 183),
    (v_template_id, '물품27_수량', 'number', false, NULL::jsonb, 184),
    (v_template_id, '물품27_예상금액', 'number', false, NULL::jsonb, 185),
    (v_template_id, '물품27_할인가', 'number', false, NULL::jsonb, 186),
    (v_template_id, '물품27_사는곳', 'text', false, NULL::jsonb, 187),
    (v_template_id, '물품27_상품번호_링크', 'textarea', false, NULL::jsonb, 188),
    (v_template_id, '물품28_물품명', 'text', false, NULL::jsonb, 189),
    (v_template_id, '물품28_예상단가', 'number', false, NULL::jsonb, 190),
    (v_template_id, '물품28_수량', 'number', false, NULL::jsonb, 191),
    (v_template_id, '물품28_예상금액', 'number', false, NULL::jsonb, 192),
    (v_template_id, '물품28_할인가', 'number', false, NULL::jsonb, 193),
    (v_template_id, '물품28_사는곳', 'text', false, NULL::jsonb, 194),
    (v_template_id, '물품28_상품번호_링크', 'textarea', false, NULL::jsonb, 195),
    (v_template_id, '물품29_물품명', 'text', false, NULL::jsonb, 196),
    (v_template_id, '물품29_예상단가', 'number', false, NULL::jsonb, 197),
    (v_template_id, '물품29_수량', 'number', false, NULL::jsonb, 198),
    (v_template_id, '물품29_예상금액', 'number', false, NULL::jsonb, 199),
    (v_template_id, '물품29_할인가', 'number', false, NULL::jsonb, 200),
    (v_template_id, '물품29_사는곳', 'text', false, NULL::jsonb, 201),
    (v_template_id, '물품29_상품번호_링크', 'textarea', false, NULL::jsonb, 202),
    (v_template_id, '물품30_물품명', 'text', false, NULL::jsonb, 203),
    (v_template_id, '물품30_예상단가', 'number', false, NULL::jsonb, 204),
    (v_template_id, '물품30_수량', 'number', false, NULL::jsonb, 205),
    (v_template_id, '물품30_예상금액', 'number', false, NULL::jsonb, 206),
    (v_template_id, '물품30_할인가', 'number', false, NULL::jsonb, 207),
    (v_template_id, '물품30_사는곳', 'text', false, NULL::jsonb, 208),
    (v_template_id, '물품30_상품번호_링크', 'textarea', false, NULL::jsonb, 209);
END $$;
