//! Port for private object storage.
//!
//! Bytes live outside PostgreSQL, so the service needs one small abstraction it
//! can point at R2 in production and at a local directory while developing.
//! Keys are generated by the server, never by a client, and the port has no
//! concept of listing or public URLs: a caller must already know the key.
//!
//! The port is the contract. The file adapter below is the provided
//! implementation for development and tests; production plugs R2 into the same
//! trait without changing any caller.

use std::{
    future::Future,
    path::{Component, Path, PathBuf},
    pin::Pin,
};

#[derive(Debug)]
pub enum StorageError {
    /// Storage is not configured, so the feature must be refused, not degraded.
    Unavailable(String),
    /// The provider refused or failed the operation.
    Failed(String),
}

impl std::fmt::Display for StorageError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Unavailable(message) => write!(formatter, "storage is unavailable: {message}"),
            Self::Failed(message) => write!(formatter, "storage failed: {message}"),
        }
    }
}

impl std::error::Error for StorageError {}

pub type StorageFuture<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;

/// Private object storage addressed by a server-generated key.
pub trait ObjectStorage: Send + Sync {
    /// Writes one object. Writing the same key again replaces the object.
    fn put<'a>(
        &'a self,
        key: &'a str,
        bytes: Vec<u8>,
        content_type: &'a str,
    ) -> StorageFuture<'a, Result<(), StorageError>>;

    /// Reads one object. An unknown key is `None`, not an error.
    fn get<'a>(&'a self, key: &'a str) -> StorageFuture<'a, Result<Option<Vec<u8>>, StorageError>>;

    /// Removes one object. Removing an unknown key is not an error.
    fn delete<'a>(&'a self, key: &'a str) -> StorageFuture<'a, Result<(), StorageError>>;
}

/// Stores objects as files under one directory.
///
/// Every object stays under the root: a key must be relative and must not
/// contain traversal components, so a malformed key cannot escape the directory.
pub struct FileStorage {
    root: PathBuf,
}

impl FileStorage {
    pub fn new(root: PathBuf) -> Self {
        Self { root }
    }

    fn path_for(&self, key: &str) -> Result<PathBuf, StorageError> {
        let relative = Path::new(key);
        if relative.as_os_str().is_empty() || relative.is_absolute() {
            return Err(StorageError::Failed(
                "object key must be a relative path".to_owned(),
            ));
        }
        for component in relative.components() {
            if !matches!(component, Component::Normal(_)) {
                return Err(StorageError::Failed(
                    "object key must not contain traversal".to_owned(),
                ));
            }
        }
        Ok(self.root.join(relative))
    }
}

impl ObjectStorage for FileStorage {
    fn put<'a>(
        &'a self,
        key: &'a str,
        bytes: Vec<u8>,
        _content_type: &'a str,
    ) -> StorageFuture<'a, Result<(), StorageError>> {
        Box::pin(async move {
            let path = self.path_for(key)?;
            if let Some(parent) = path.parent() {
                tokio::fs::create_dir_all(parent)
                    .await
                    .map_err(|error| StorageError::Failed(error.to_string()))?;
            }
            tokio::fs::write(&path, bytes)
                .await
                .map_err(|error| StorageError::Failed(error.to_string()))?;
            Ok(())
        })
    }

    fn get<'a>(&'a self, key: &'a str) -> StorageFuture<'a, Result<Option<Vec<u8>>, StorageError>> {
        Box::pin(async move {
            let path = self.path_for(key)?;
            match tokio::fs::read(&path).await {
                Ok(bytes) => Ok(Some(bytes)),
                Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
                Err(error) => Err(StorageError::Failed(error.to_string())),
            }
        })
    }

    fn delete<'a>(&'a self, key: &'a str) -> StorageFuture<'a, Result<(), StorageError>> {
        Box::pin(async move {
            let path = self.path_for(key)?;
            match tokio::fs::remove_file(&path).await {
                Ok(()) => Ok(()),
                Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
                Err(error) => Err(StorageError::Failed(error.to_string())),
            }
        })
    }
}

#[cfg(test)]
mod tests {
    use super::{FileStorage, ObjectStorage};

    #[tokio::test]
    async fn file_storage_round_trips_and_refuses_traversal() {
        let root = std::env::temp_dir().join(format!("storage-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        let storage = FileStorage::new(root.clone());

        storage
            .put("tenants/a/attachments/1", b"hello".to_vec(), "text/plain")
            .await
            .expect("put");
        assert_eq!(
            storage.get("tenants/a/attachments/1").await.expect("get"),
            Some(b"hello".to_vec())
        );
        assert_eq!(storage.get("tenants/a/missing").await.expect("get"), None);

        storage
            .delete("tenants/a/attachments/1")
            .await
            .expect("delete");
        assert_eq!(
            storage.get("tenants/a/attachments/1").await.expect("get"),
            None
        );
        // Removing something twice is not an error.
        storage
            .delete("tenants/a/attachments/1")
            .await
            .expect("delete again");

        assert!(
            storage
                .put("../escape", b"x".to_vec(), "text/plain")
                .await
                .is_err()
        );
        assert!(
            storage
                .put("/absolute", b"x".to_vec(), "text/plain")
                .await
                .is_err()
        );
        assert!(storage.get("tenants/../escape").await.is_err());

        let _ = std::fs::remove_dir_all(&root);
    }
}
