//! Port for private object storage.
//!
//! Bytes live outside PostgreSQL, so the service needs one small abstraction it
//! can point at R2 in production and at a local directory while developing.
//! Keys are generated by the server, never by a client, and the port has no
//! concept of listing or public URLs: a caller must already know the key.

use std::{future::Future, pin::Pin};

#[derive(Debug)]
pub enum StorageError {
    /// Storage is not configured, so the feature must be refused, not degraded.
    Unavailable(String),
    /// The provider refused or failed the operation.
    Failed(String),
}

impl std::fmt::Display for StorageError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Unavailable(message) => write!(formatter, "storage is unavailable: {message}"),
            Self::Failed(message) => write!(formatter, "storage failed: {message}"),
        }
    }
}

impl std::error::Error for StorageError {}

pub type StorageFuture<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;

/// Private object storage addressed by a server-generated key.
pub trait ObjectStorage: Send + Sync {
    /// Writes one object. Writing the same key again replaces the object.
    fn put<'a>(
        &'a self,
        key: &'a str,
        bytes: Vec<u8>,
        content_type: &'a str,
    ) -> StorageFuture<'a, Result<(), StorageError>>;

    /// Reads one object. An unknown key is `None`, not an error.
    fn get<'a>(&'a self, key: &'a str) -> StorageFuture<'a, Result<Option<Vec<u8>>, StorageError>>;

    /// Removes one object. Removing an unknown key is not an error.
    fn delete<'a>(&'a self, key: &'a str) -> StorageFuture<'a, Result<(), StorageError>>;
}
